config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products, only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.find(params[:id])
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "BigBag Store"
    if page_title.blank?
      base_title
    else
      "#{page_title}-#{base_title}"
    end
  end
end

app/views/layouts/_footer.html.erb
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header clearfix">
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li><!-- <span><a data-toggle="modal" href='.login-modal'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span> --></li>
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <form id="form01" action="product-grid-left-sidebar.html" method="post">
                  <li>
                    <span class="input-group">
                      <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                    </span>
                  </li>
                </form>
              </ul>
            </li>
            <li class="dropdown">
              <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand"><%= link_to image_tag("img/logo.png", :alt => ""), potepan_path %></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "HOME", potepan_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>

app/views/layouts/_login_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<!script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<!script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_signup_modal.html.erb
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%=full_title(yield(:title))%></title>
    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header'%>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/signup_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/products/_item_images.html.erb
<div id="carousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">

    # 少し理解できなかったので他の方のを参考に書きました。↓

    <% product.images.each_with_index do |image, i| %>
      <div class="item <%= "active" if i.zero? %>" data-thumb= "<%= i %>">
        <%= image_tag(image.attachment(:large)) %>
      </div>
    <% end %>
  </div>
</div>
<div class="clearfix">
  <div id="thumbcarousel" class="carousel slide" data-interval="false">
    <div class="carousel-inner">
      <% product.images.each_with_index do |image, i| %>
        <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb"><%= image_tag(image.attachment(:small)) %></div>
      <% end %>
    </div>
    <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</div>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag("img/products/products-01.jpg", :alt => "products-img") %>
      </div>
      <div class="productCaption clearfix">
        <h5>Nike Sportswear</h5>
        <h3>199円</h3>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag("img/products/products-02.jpg", :alt => "products-img") %>
      </div>
      <div class="productCaption clearfix">
        <h5>Dip Dyed Sweater</h5>
        <h3>249円</h3>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag("img/products/products-03.jpg", :alt => "products-img") %>
      </div>
      <div class="productCaption clearfix">
        <h5>Scarf Ring Corner</h5>
        <h3>179円</h3>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag("img/products/products-04.jpg", :alt => "products-img") %>
      </div>
      <div class="productCaption clearfix">
        <h5>Sun Buddies</h5>
        <h3>149円</h3>
      </div>
    </div>
  </div>
</div>

app/views/potepan/products/show.html.erb
<%= provide(:title, @product.name) %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "HOME", potepan_path %>
          </li>
          <li class="active"><%= @product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
           <%= render 'item_images', product: @product %>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li><a href="product_grid_left_sidebar.html"><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</a></li>
              <!-- <li><a href="#"><i class="fa fa-plus" aria-hidden="true"></i>Share This</a></li> -->
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
              <!--   <option value="0">Qty</option> -->
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
            <!-- <div class="tabArea">
              <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#details">details</a></li>
                <li><a data-toggle="tab" href="#about-art">about art</a></li>
                <li><a data-toggle="tab" href="#sizing">sizing</a></li>
                <li><a data-toggle="tab" href="#shipping">shipping</a></li>
              </ul>
              <div class="tab-content">
                <div id="details" class="tab-pane fade in active">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                  <ul class="list-unstyled">
                    <li>Black, Crew Neck</li>
                    <li>75% Cotton, 25% Rayon</li>
                    <li>Waterbased Ink</li>
                    <li>Wash Cold, dry low</li>
                  </ul>
                </div>
                <div id="about-art" class="tab-pane fade">
                  <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis condimentum nibh dolor ut tortor. Donec egestas tortor quis mattis gravida. Ut efficitur elit vitae dignissim volutpat. </p>
                </div>
                <div id="sizing" class="tab-pane fade">
                  <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam varius cursus nisi, sed elementum sem sagittis at. Nulla tellus massa, vestibulum a commodo facilisis, pulvinar convallis nunc.</p>
                </div>
                <div id="shipping" class="tab-pane fade">
                  <p>Mauris lobortis augue ex, ut faucibus nisi mollis ac. Sed volutpat scelerisque ex ut ullamcorper. Cras at velit quis sapien dapibus laoreet a id odio. Sed sit amet accumsan ante, eu congue metus. Aenean eros tortor, cursus quis feugiat sed, vestibulum vel purus.</p>
                </div>
              </div>
            </div> -->
          </div>
        </div>
      </div>
    </div>
    <%= render 'related_products'%>
  </div>
</section>

app/views/potepan/sample/checkout_complete.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Order Completed - BIGBAG Store</title>

    <!-- PLUGINS CSS STYLE -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

    <!-- CUSTOM CSS -->
    <link href="css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="css/colors/default.css" id="option_color">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="main-wrapper">

      <!-- HEADER -->
      <div class="header clearfix">

        <!-- TOPBAR -->
        <div class="topBar">
          <div class="container">
            <div class="row">
              <div class="col-md-6 hidden-sm hidden-xs">
                <ul class="list-inline">
                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                </ul>
              </div>
              <div class="col-md-6 col-xs-12">
                <ul class="list-inline pull-right">
                  <li><!-- <span><a data-toggle="modal" href='.login-modal'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span> --></li>
                  <li class="dropdown searchBox">
                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                      <form  id="form01" action="product-grid-left-sidebar.html" method="post">
                      <li>
                        <span class="input-group">
                          <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                          <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                        </span>
                      </li>
                      </form>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- NAVBAR -->
        <nav class="navbar navbar-main navbar-default" role="navigation">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.html"><%= image_tag("logo.png") %></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
              <ul class="nav navbar-nav navbar-right">
                <li class=""><a href="index.html">Home</a></li>
                <li class="dropdown megaDropMenu">
                  <a href="product-grid-left-sidebar.html" class="dropdown-toggle">Shop</b></a>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div>
        </nav>

      </div>

      <!-- LIGHT SECTION -->
      <section class="lightSection clearfix pageHeader">
        <div class="container">
          <div class="row">
            <div class="col-xs-6">
              <div class="page-title">
                <h2>thanks message</h2>
              </div>
            </div>
            <div class="col-xs-6">
              <ol class="breadcrumb pull-right">
                <li>
                  <a href="index.html">Home</a>
                </li>
                <li class="active">thanks message</li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      <!-- MAIN CONTENT SECTION -->
      <section class="mainContent clearfix setp5">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="thanksContent">
                <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
                <h3>Shipping Details</h3>
                <div class="thanksInner">
                  <div class="row">
                    <div class="col-sm-6 col-xs-12 tableBlcok">
                      <address>
                        <span>Shipping address:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                        <span>Email:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                        <span>Phone:</span> +884 5452 6432
                      </address>
                    </div>
                    <div class="col-sm-6 col-xs-12">
                      <div class="well">
                        <h2><small>Order ID</small>9547</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- FOOTER -->
      <!-- COPY RIGHT -->
      <div id="footer" class="copyRight clearfix">
        <div class="container">
          <div class="row">
            <div class="col-sm-7 col-xs-12">
              <p>&copy; 2016-<%= Time.now.year %> Copyright Potepan Store .</p>
            </div>
            <div class="col-sm-5 col-xs-12">
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- LOGIN MODAL -->
    <div class="modal fade" id="login" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title">log in</h3>
          </div>
          <div class="modal-body">
            <form action="" method="POST" role="form">
              <div class="form-group">
                <label for="login-email">Enter Email</label>
                <input type="email" class="form-control" id="login-email">
              </div>
              <div class="form-group">
                <label for="login-password">Password</label>
                <input type="password" class="form-control" id="login-password">
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Remember Me
                </label>
              </div>
              <button type="submit" class="btn btn-primary btn-block">log in</button>
              <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- SIGN UP MODAL -->
    <div class="modal fade" id="signup" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title">Create an account</h3>
          </div>
          <div class="modal-body">
            <form action="" method="POST" role="form">
              <div class="form-group">
                <label for="signup-email">Enter Email</label>
                <input type="email" class="form-control" id="signup-email">
              </div>
              <div class="form-group">
                <label for="signup-password">Password</label>
                <input type="password" class="form-control" id="signup-password">
              </div>
              <div class="form-group">
                <label for="signup-password-confirmation">Confirm Password</label>
                <input type="password" class="form-control" id="signup-password-confirmation">
              </div>
              <button type="submit" class="btn btn-primary btn-block">Sign up</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>